In [131]:
n = 1
L = 8*n + 4                        #number of lattice sites
t = 1                              #hopping constant
Ne = Int(L / 2)                    #number of electrons


function Hamiltonian(L,t)
    H = zeros(2*L, 2*L)
    H[1,L] = -t
    H[L,1] = -t
    H[2L,L+1] = -t
    H[L+1,2L] = -t
    for i=1:2*L
      for j=1:2*L
        if i == j + 1 || i == j - 1
          H[i,j] = -t
        end 
      end
    end
    H[L,L+1]=0
    H[L+1,L]=0
    return H
end

H = Hamiltonian(L,t)

24×24 Matrix{Float64}:
  0.0  -1.0   0.0   0.0   0.0   0.0  …   0.0   0.0   0.0   0.0   0.0   0.0
 -1.0   0.0  -1.0   0.0   0.0   0.0      0.0   0.0   0.0   0.0   0.0   0.0
  0.0  -1.0   0.0  -1.0   0.0   0.0      0.0   0.0   0.0   0.0   0.0   0.0
  0.0   0.0  -1.0   0.0  -1.0   0.0      0.0   0.0   0.0   0.0   0.0   0.0
  0.0   0.0   0.0  -1.0   0.0  -1.0      0.0   0.0   0.0   0.0   0.0   0.0
  0.0   0.0   0.0   0.0  -1.0   0.0  …   0.0   0.0   0.0   0.0   0.0   0.0
  0.0   0.0   0.0   0.0   0.0  -1.0      0.0   0.0   0.0   0.0   0.0   0.0
  0.0   0.0   0.0   0.0   0.0   0.0      0.0   0.0   0.0   0.0   0.0   0.0
  0.0   0.0   0.0   0.0   0.0   0.0      0.0   0.0   0.0   0.0   0.0   0.0
  0.0   0.0   0.0   0.0   0.0   0.0      0.0   0.0   0.0   0.0   0.0   0.0
  0.0   0.0   0.0   0.0   0.0   0.0  …   0.0   0.0   0.0   0.0   0.0   0.0
 -1.0   0.0   0.0   0.0   0.0   0.0      0.0   0.0   0.0   0.0   0.0   0.0
  0.0   0.0   0.0   0.0   0.0   0.0      0.0   0.0   0.0   0.0   0.0  -1.0
  

In [132]:
using LinearAlgebra
U = eigvecs(H)  #unitary matrix
Udag = inv(U)   #U^-1
E = eigvals(H)  #eigenvalues of H

24-element Vector{Float64}:
 -2.0000000000000013
 -1.9999999999999991
 -1.7320508075688772
 -1.732050807568877
 -1.732050807568877
 -1.7320508075688767
 -1.0000000000000002
 -0.9999999999999996
 -0.9999999999999996
 -0.9999999999999996
 -2.2058985591457146e-16
 -3.826984288205141e-18
 -4.253626010865457e-20
  2.2690771583394997e-16
  0.999999999999999
  0.9999999999999991
  0.9999999999999991
  0.9999999999999994
  1.732050807568876
  1.7320508075688767
  1.7320508075688774
  1.7320508075688776
  2.000000000000001
  2.000000000000001

In [146]:
function U1(A, Ne) #take the first Ne columns
    U_en = A[:,1:Ne]
    return U_en
end

U_en = U1(U,Ne)

24×6 Matrix{Float64}:
 -0.288675   0.0       -0.204124      0.0           0.353553      0.0
 -0.288675   0.0       -0.353553      0.0           0.204124      0.0
 -0.288675   0.0       -0.408248      0.0           1.84172e-15   0.0
 -0.288675   0.0       -0.353553      0.0          -0.204124      0.0
 -0.288675   0.0       -0.204124      0.0          -0.353553      0.0
 -0.288675   0.0        3.92523e-17   0.0          -0.408248      0.0
 -0.288675   0.0        0.204124      0.0          -0.353553      0.0
 -0.288675   0.0        0.353553      0.0          -0.204124      0.0
 -0.288675   0.0        0.408248      0.0           1.92023e-15   0.0
 -0.288675   0.0        0.353553      0.0           0.204124      0.0
 -0.288675   0.0        0.204124      0.0           0.353553      0.0
 -0.288675   0.0        0.0           0.0           0.408248      0.0
  0.0       -0.288675   0.0          -0.204124      0.0           0.353553
  0.0       -0.288675   0.0          -0.353553      0.0        

In [147]:
function occupied_states(v)           #writes a vector that contains the positions in the vector "state" of the occuppied states
    occ_states = []
    for i = 1 : 2*L                   #example: state = [0,1,0,1,1] -> occupied_states = [2,4,5]
        if v[i] == 1
            append!(occ_states, i )
        end
    end
    return occ_states
end
    

function U_tilde(A,v)                  #takes just the rows related to occupied states, Ne*Ne matrix
    U_tild = []
    U_tild = A[occupied_states(v),:]
    return U_tild
end

U_tilde (generic function with 1 method)

In [148]:
state = [1,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,1]      #initial state

U_1 = U_tilde(U_en,state)                       #initial U tilde

state_1 = [1,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,1]    #|x'>

U_2 = U_tilde(U_en,state_1)                     #new U tilde

ratio = det(U_2) / det(U_1)                    #ratio of determinants of U tilde matrices

1.5773502691896293

In [149]:
#Jastrow factor
Jastrow_ratio = 1

1

In [150]:
function MC(q0=0,delta=0.1,nsteps=1000,seed=None):                    #from Bussi, useful for inspiration
    if seed is not None:
        np.random.seed(seed)
    q=q0
    traj=[]
    for istep in range(nsteps):
        qtry=q+(2*np.random.rand()-1)*delta
        energy_try=0.5*kappa*qtry**2     #1/2 k q^2
        deltae=energy_try-energy
        if deltae<=0.0:          #take acceptance 1 if the energy decrease
            acceptance=1.0
        else:
            acceptance =  ratio**2 * Jastrow_ratio**2   #acceptance 
        if acceptance >=1.0 or acceptance>np.random.rand(): #metropolis rule
            q=qtry
            energy=energy_try
        traj.append(q)
    return np.array(traj)

LoadError: syntax: newline not allowed after ":" used for quoting

In [151]:
state = [1,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,1]      #initial state

function move(v1)                              #generate a random move from a random occupied state
    v = copy(v1)
    len_v = length(v)
    x = occupied_states(v)
    n = length(x)
    i = rand(1:n)
    v[x[i]] = 0
    if 1 < x[i] < length(v)
        v[x[i]+2*rand(0:1)-1] += 1             #random +-1 move if not at boundaries
    elseif x[i]==1                             #if in position 1 move either to 2 or to n
        if 2*rand(0:1)-1 < 0
            v[len_v] += 1
        else
            v[2] += 1
        end
    else 
        if 2*rand(0:1)-1 < 0                    #if in position n move either to n-1 or to 1
            v[len_v-1] += 1
        else
            v[1] += 1
        end 
    end
    return v
end

move (generic function with 1 method)

In [105]:
function MC
    state_new = move(state)   
    acceptance =  ratio**2 * Jastrow_ratio**2       #acceptance 
    if acceptance >=1.0 or acceptance>rand()        #metropolis rule
        
        #update T jastrow
        U_2 = U_tilde(U_en,state_new)                     #new U tilde
        
        ratio = det(U_2) / det(U_1)                    #ratio of determinants of U tilde matrices
        state = copy(state_new)
    end
    
end  
        

LoadError: syntax: expected "end" in definition of function "MC"