In [2]:
L = 8
t = 1
function Hamiltonian(L,t)
    H = zeros(2*L, 2*L)
    H[1,L] = -t
    H[L,1] = -t
    H[2L,L+1] = -t
    H[L+1,2L] = -t
    for i=1:2*L
      for j=1:2*L
        if i == j + 1 || i == j - 1
          H[i,j] = -t
        end 
      end
    end
    H[L,L+1]=0
    H[L+1,L]=0
    return H
end

H = Hamiltonian(L,t)

16×16 Matrix{Float64}:
  0.0  -1.0   0.0   0.0   0.0   0.0  …   0.0   0.0   0.0   0.0   0.0   0.0
 -1.0   0.0  -1.0   0.0   0.0   0.0      0.0   0.0   0.0   0.0   0.0   0.0
  0.0  -1.0   0.0  -1.0   0.0   0.0      0.0   0.0   0.0   0.0   0.0   0.0
  0.0   0.0  -1.0   0.0  -1.0   0.0      0.0   0.0   0.0   0.0   0.0   0.0
  0.0   0.0   0.0  -1.0   0.0  -1.0      0.0   0.0   0.0   0.0   0.0   0.0
  0.0   0.0   0.0   0.0  -1.0   0.0  …   0.0   0.0   0.0   0.0   0.0   0.0
  0.0   0.0   0.0   0.0   0.0  -1.0      0.0   0.0   0.0   0.0   0.0   0.0
 -1.0   0.0   0.0   0.0   0.0   0.0      0.0   0.0   0.0   0.0   0.0   0.0
  0.0   0.0   0.0   0.0   0.0   0.0      0.0   0.0   0.0   0.0   0.0  -1.0
  0.0   0.0   0.0   0.0   0.0   0.0     -1.0   0.0   0.0   0.0   0.0   0.0
  0.0   0.0   0.0   0.0   0.0   0.0  …   0.0  -1.0   0.0   0.0   0.0   0.0
  0.0   0.0   0.0   0.0   0.0   0.0     -1.0   0.0  -1.0   0.0   0.0   0.0
  0.0   0.0   0.0   0.0   0.0   0.0      0.0  -1.0   0.0  -1.0   0.0   0.0
  

In [3]:
using LinearAlgebra
U = eigvecs(H)  #unitary matrix
Udag = inv(U)   #U^-1
E = eigvals(H)  #eigenvalues of H

-2.0000000000000004

In [8]:
function U1(A, Ne) #take the first Ne columns
    U_1 = A[:,1:4]
    return U_1
end

U_1 = U1(U,4)

16×4 Matrix{Float64}:
 -0.353553   0.0        0.353553      0.0
 -0.353553   0.0        0.5           0.0
 -0.353553   0.0        0.353553      0.0
 -0.353553   0.0       -5.55112e-17   0.0
 -0.353553   0.0       -0.353553      0.0
 -0.353553   0.0       -0.5           0.0
 -0.353553   0.0       -0.353553      0.0
 -0.353553   0.0        0.0           0.0
  0.0       -0.353553   0.0           0.353553
  0.0       -0.353553   0.0           0.5
  0.0       -0.353553   0.0           0.353553
  0.0       -0.353553   0.0          -5.55112e-17
  0.0       -0.353553   0.0          -0.353553
  0.0       -0.353553   0.0          -0.5
  0.0       -0.353553   0.0          -0.353553
  0.0       -0.353553   0.0           0.0

In [18]:
function U_tilde(A,state)                  #takes just the rows related to occupied states, Ne*Ne matrix
    U_tild = []
    occupied_states = []
    for i = 1 : 2*L
        if state[i] == 1
            append!(occupied_states, i )
        end
    end
    U_tild = A[occupied_states,:]
    return U_tild
end

  

4×4 Matrix{Float64}:
 -0.353553   0.0       0.353553   0.0
 -0.353553   0.0       0.5        0.0
  0.0       -0.353553  0.0        0.353553
  0.0       -0.353553  0.0       -0.353553

In [19]:
state = [1,1,0,0,0,0,0,0,0,0,1,0,1,0,0,0]      #initial state

U_2 = U_tilde(U_1,state)                       #initial U tilde

state_1 = [1,1,0,0,0,0,0,0,0,0,1,0,0,1,0,0]    #|x'>

U_3 = U_tilde(U_1,state_1)                     #new U tilde

ratio = det(U_3) / det(U_2)                    #ratio of determinants of U tilde matrices


1.2071067811865481